---
- name: "kodecloud ecommerce app"
  hosts: localhost
  become: yes
  vars:
    db_name: ecomdb
    db_user: ecomuser
    db_password: ecompassword
    db_endpoint: localhost
  roles:
    - mysql_db
    - apache_web
  tasks:
    #- include: tasks/package_install.yml
    - include: tasks/db_deploy.yml
    - include: tasks/web_deploy.yml
