- name: debug tasks
  hosts: localhost
  vars:
    var1: value1
  tasks:
    - debug:
        msg:  "test message from var {{ var1 }}"
    - debug:  var=ansible_default_ipv4.address
    - debug:  var=ansible_hostname
