---
# tasks file for apache_web
    - name: install web package
      apt:
        name: '{{ item }}'
        state: latest
      with_items:
        - firewalld
        - apache2
        - php
        - php-mysql
    - name: enable service
      service:
        name: '{{ item }}'
        state: started
        enabled: yes
      with_items:
        - firewalld
        - apache2
